BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "users" (
	"id"	INTEGER NOT NULL UNIQUE,
	"enabled"	INTEGER NOT NULL DEFAULT 0,
	"price_from"	INTEGER NOT NULL DEFAULT 0,
	"price_to"	INTEGER NOT NULL DEFAULT 0,
	"rooms_from"	INTEGER NOT NULL DEFAULT 0,
	"rooms_to"	INTEGER NOT NULL DEFAULT 0,
	"year_from"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("id")
);
CREATE TABLE IF NOT EXISTS "posts" (
	"id"	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	"url"	INTEGER NOT NULL UNIQUE
);
CREATE UNIQUE INDEX IF NOT EXISTS "index_posts_url" ON "posts" (
	"url"
);
COMMIT;
